# .github/workflows/update_price.yml

name: 游늳 Update Binance P2P + BCV Price

on:
  # Corre cada minuto; si prefieres cada 5 minutos, cambia a '*/5 * * * *'
  schedule:
    - cron: '*/1 * * * *'
  # Permite ejecutarlo manualmente desde la pesta침a Actions
  workflow_dispatch:

jobs:
  update_prices:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Instalar 'jq' (necesario para parsear/armar JSON)
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # 3) Ejecutar el script que genera price.json
      - name: Ejecutar fetch_binance_p2p.sh
        run: |
          chmod +x scripts/fetch_binance_p2p.sh
          ./scripts/fetch_binance_p2p.sh

      # 4) Commit + push de price.json (solo si cambi칩)
      - name: Commit y push de price.json
        run: |
          # Configuramos un usuario gen칠rico para commits desde Actions
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # A침adimos price.json al 치rea (si no cambi칩, git add no falla por '|| true')
          git add price.json || true

          # Si no hay cambios en price.json, salimos sin error
          git diff --quiet --exit-code && echo "No hay cambios en price.json" && exit 0

          # Si s칤 hay cambios, hacemos commit y push
          git commit -m "Actualiza price.json: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push origin main
      - name: Enviar mensaje a Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELE_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELE_CHAT_ID }}
        run: |
          chmod +x scripts/send_telegram.sh
          ./scripts/send_telegram.sh "$BOT_TOKEN" "$CHAT_ID"