name: Update price.json

on:
  schedule:
    - cron: '*/1 * * * *'   # cada minuto, por ejemplo
  workflow_dispatch:       # opcional: para correr manualmente si quieres

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (jq & curl)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch Binance P2P & update price.json
        run: |
          chmod +x scripts/fetch_binance_p2p.sh
          ./scripts/fetch_binance_p2p.sh

      - name: Commit & push price.json if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add price.json || true
          git diff --quiet --exit-code || (git commit -m "chore: update price.json @ $(date -u +'%Y-%m-%dT%H:%M:%SZ')" && git push)
